repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.6.0
    hooks:
      - id: clang-format
        args: [--style=file]  # to load .clang-format
      - id: clang-tidy
        args: [--checks=.clang-tidy] # path/to/.clang-tidy
