#ifndef NEAREST_NEIGHBOR_H
#define NEAREST_NEIGHBOR_H

// FUNCAO RESPONSAVEL POR REALIZAR O CALCULO DO TAMANHO DO VETOR COM BASE NA
// SEQUENCIA INFORMADA PELO USUÁRIO
int calculaTamanhoVetor(int, int);

// FUNÇÃO RESPONSAVEL POR REALIZAR O CALCULO DA RAIZ
double calculaRaiz(double *, int, int, int, int);

// FUNÇÃO RESPONSAVEL POR ENCONTRAR O VIZINHO MAIS PROXIMO NA MATRIZ E ARMAZENAR
// A SUA RAIZ E RESPECTVO INDICE
int *extraiVizinhoMaisProximo(int, double **, float *, int);

#endif
